# Generated by Django 5.2.7 on 2025-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='habitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(blank=True)),
                ('habit_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration', models.DurationField(blank=True)),
            ],
        ),
    ]
