# Generated by Django 5.1.12 on 2025-11-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
